var searchData=
[
  ['optiga_5fcalc_5fhash',['optiga_calc_hash',['../d0/d20/structoptiga__calc__hash.html',1,'']]],
  ['optiga_5fcalc_5fsign',['optiga_calc_sign',['../d2/d1d/structoptiga__calc__sign.html',1,'']]],
  ['optiga_5fcalc_5fssec',['optiga_calc_ssec',['../da/ddc/structoptiga__calc__ssec.html',1,'']]],
  ['optiga_5fcmd',['optiga_cmd',['../d3/d87/structoptiga__cmd.html',1,'']]],
  ['optiga_5fcmd_5fqueue_5fslot',['optiga_cmd_queue_slot',['../dc/d84/structoptiga__cmd__queue__slot.html',1,'']]],
  ['optiga_5fcomms',['optiga_comms',['../de/dc7/structoptiga__comms.html',1,'']]],
  ['optiga_5fcontext',['optiga_context',['../d8/df6/structoptiga__context.html',1,'']]],
  ['optiga_5fcrypt',['optiga_crypt',['../d7/d2c/structoptiga__crypt.html',1,'']]],
  ['optiga_5fcrypt_5fparams',['optiga_crypt_params',['../d3/d89/unionoptiga__crypt__params.html',1,'']]],
  ['optiga_5fderive_5fkey',['optiga_derive_key',['../d2/dec/structoptiga__derive__key.html',1,'']]],
  ['optiga_5fenc_5fdec_5fasym',['optiga_enc_dec_asym',['../dd/d4a/structoptiga__enc__dec__asym.html',1,'']]],
  ['optiga_5fgen_5fkeypair',['optiga_gen_keypair',['../d9/d66/structoptiga__gen__keypair.html',1,'']]],
  ['optiga_5fget_5fdata_5fobject',['optiga_get_data_object',['../d0/d1b/structoptiga__get__data__object.html',1,'']]],
  ['optiga_5fget_5frandom',['optiga_get_random',['../d9/d89/structoptiga__get__random.html',1,'']]],
  ['optiga_5fhash_5fcontext',['optiga_hash_context',['../d8/d24/structoptiga__hash__context.html',1,'']]],
  ['optiga_5fset_5fdata_5fobject',['optiga_set_data_object',['../d0/d11/structoptiga__set__data__object.html',1,'']]],
  ['optiga_5fset_5fobject_5fprotected_5fparams',['optiga_set_object_protected_params',['../db/db9/structoptiga__set__object__protected__params.html',1,'']]],
  ['optiga_5futil',['optiga_util',['../da/df9/structoptiga__util.html',1,'']]],
  ['optiga_5futil_5fparams',['optiga_util_params',['../db/d72/unionoptiga__util__params.html',1,'']]],
  ['optiga_5fverify_5fsign',['optiga_verify_sign',['../d7/d33/structoptiga__verify__sign.html',1,'']]]
];
